version: '3.1'

services:

#   web:
#     image: nginx
#     container_name: auth-nginx
#     restart: always
#     ports:
#       - 8080:80
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      ENV: DEV
      DB_NAME: ${DB_NAME}
      DB_PASS: ${DB_PASS}
      API_KEY: ${API_KEY}
    volumes:
      - ./api:/api
    restart: always
    container_name: auth_api
    links:
      - db

  db:
     image: mysql:latest
     command: --default-authentication-plugin=mysql_native_password
     restart: always
     container_name: auth_db
     volumes:
       - ./db/mysql:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: ${DB_PASS}

  myadmin:
     image: phpmyadmin/phpmyadmin
     restart: always
     links:
       - db
     ports:
       - "8082:80"
